---
title: "Intro to Data Visualization"
author: "Collin J. Closek"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
```{r load packages, warning=FALSE, message=FALSE}
library(dplyr)
library(readr)
library(tidyr)
library(forcats)
library(ggplot2)
library(leaflet)
library(DT)
library(scales)
```

##Read data
```{r read data}
escapement <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e")
```

Data source: https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e
Downloaded on April 5, 2023

## Explore data
```{r explore}
## Check out column names
colnames(escapement)

## Peak at each column and class
glimpse(escapement)

## From when to when
range(escapement$sampleDate)

## How frequent?
head(escapement$sampleDate)
tail(escapement$sampleDate)

## Which species?
unique(escapement$Species)
```

## Getting out data ready to plot annual escapements for select species
```{r cleaning}
annual_esc <- escapement %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep="-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escape = sum(DailyCount)) %>%
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))

unique(annual_esc$Species)
head(annual_esc)

```

## Plotting with `ggplot`

##Essential conponents
```{r essentials}
## Option 1
ggplot(data = annual_esc,
       aes(x = Species,
           y = escape))+
  geom_col()

## Option 2
ggplot(data = annual_esc)+
  geom_col(aes(x = Species, 
               y = escape))

## Option 3
ggplot()+
  geom_col(data = annual_esc,
           aes(x = Species, 
               y = escape))
```


## Different geoms

**Boxplot**
```{r geom_boxplot}

annual_esc %>% 
  filter(Year == 1974, 
         Species %in% c("Chum", "Pink")) %>% 
  ggplot(aes(x = Species,
             y = escape))+
  geom_boxplot()
```


**Line and point**
```{r geom_line}
annual_esc %>% 
  filter(Species == "Sockeye",
         SASAP.Region == "Bristol Bay") %>% 
  ggplot(aes(x = Year,
             y = escape)) +
  geom_line() +
  geom_point()
```


## Customizing the plot
```{r}
ggplot(annual_esc, 
       aes(x = Species,
           y = escape,
           fill = "cyan"))+
  geom_col()
```

fill = cyan outside the `aes()`
```{r}

ggplot(annual_esc, 
       aes(x = Species,
           y = escape))+
  geom_col(fill = "cyan")
```

adding colors by region
```{r}
ggplot(annual_esc,
       aes(x = Species,
           y = escape, 
           fill = SASAP.Region))+
  geom_col()
```


